version: '3'

services:
  db:
    image: postgres
  web:
    build: .
    command: ["./wait-for.sh", "db:5432", "--", "python", "manage.py", "runserver", "0.0.0.0:8000"]
    depends_on:
      - db
    env_file:
      - web.env
    volumes:
      - .:/django
    ports:
      - "8001:8000"
    tty: true
    stdin_open: true
