# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-30 05:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('confirm', '0002_auto_20170530_0549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirmation',
            name='info',
        ),
    ]
