from . import env

CONFIRMATION_EMAIL = env.CONFIRMATION_EMAIL
DOMAIN = env.DOMAIN
ANYMAIL = {
    'MAILGUN_API_KEY': env.MAILGUN_API_KEY,
    'MAILGUN_SENDER_DOMAIN': 'mg.affirmative.site',
}
REQUEST_CONFIRM_URL = env.REQUEST_CONFIRM_URL
